name: Depoly to Code Engine

on:
  push:
    branches:
      - main
      - master

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Deploy Application to Code Engine
      uses: skywalkeretw/ibm-code-engine-github-action@v1
      with:
        api-key: ${{ secrets.IBM_IAM_API_KEY }}
        resource-group: 'default'
        region: 'eu-de'
        project: 'luke-test-project'
        entity: 'app'
        name: 'luke-test-app'
        build-source: '.'
        cpu: 1
        memory: 4G

